Repository anas-elgarhy/cmus-rpc-rs, pull requests merged in 2022-10, with the labels that each got.

#16 Update README.md
  README.md
Labels: bug, hacktoberfest-accepted

#17 New translated README file is added. Main README file is modified with the link to translations.
  README.md
  translations/README-jp.md
Labels: documentation, hacktoberfest-accepted

#18 Update README.md
  README.md
Labels: hacktoberfest-accepted
